### ISSUE TITLE
restservice.py crashes when no log folder is present in current working directory

### ISSUE THREAD

**Issue by ggroener** [smartyal/21datalab#2]
When executing a newly cloned repository, the first call 
```
python restservice.py occupancydemo
```
fails with a FileNotFoundError, complaining that ./log/model.log is not found since the log folder does not exist.

**Comment by smartyal** [comment]
fixed in https://github.com/smartyal/21datalab/commit/aa14f1a99d4e7b4a0d788318c5eb7f898243fa2c
